### PR TITLE
fix #8: GIMP 3 / GTK3 migration

### LINKED ISSUE #8: GIMP 3 / GTK3 migration
The migration to GTK3 will likely break the plugin. Deprecated GTK and libgimp function calls will need to be replaced. 

No action will be taken until after the GIMP 3 release. This is just a placeholder for now.

Also see: 
* https://github.com/bootchk/resynthesizer/issues/59
* https://wiki.gimp.org/wiki/Roadmap#GIMP_3.0

### PR DESCRIPTION
**Pull request by zvezdochiot**
:warning: This is just a recipe (template). Adapt for yourself. Take PR is not necessary.

### CODE REVIEW

**Comment by bbbbbr** [comment]
:+1:  Thanks for submitting this PR and demonstrating the approach. It's a good idea.

Other projects have focus right now, so I probably won't move on this and GTK3 for a while. I will revisit this in the future.

**Comment by zvezdochiot** [comment]
Hi @bbbbbr .

:question: To choose? What for? You can have both GTK2 and GTK3. In two separate folders (`src/gtk2`,`src/gtk3`). This is the point of this approach.

:information_source: You can have two `Makefile`: `Makefile.gtk2` and `Makefile.gtk3`.

**Comment by bbbbbr** [comment]
Perhaps a misunderstanding, I did not say "choose". :) 
Yes, it is possible to support both as you demonstrate.

I mean to say: I will probably not work on this until GIMP 3 is out, at which point I will need to add GTK3 support in some form or another.

**Comment by zvezdochiot** [comment]
So early yet. To work out in advance is something “tear your eyes out”. :smile:

**Comment by zvezdochiot** [comment]
no actual.

**Pull request closed without merging**
